FROM tiangolo/meinheld-gunicorn-flask:python3.7


# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
COPY ./server.py /app/main.py

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY . /app/
